package dto;
// Generated Mar 21, 2014 5:50:47 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Interest generated by hbm2java
 */
public class Interest  implements java.io.Serializable {


     private int id;
     private String name;
     private Set users = new HashSet(0);

    public Interest() {
    }

	
    public Interest(int id) {
        this.id = id;
    }
    public Interest(int id, String name, Set users) {
       this.id = id;
       this.name = name;
       this.users = users;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


