package dto;
// Generated Mar 22, 2014 7:05:21 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int id;
     private Category category;
     private String name;
     private Double price;
     private Integer stock;
     private String photo;
     private String description;
     private Set purchases = new HashSet(0);

    public Product() {
    }

	
    public Product(int id, Category category) {
        this.id = id;
        this.category = category;
    }
    public Product(int id, Category category, String name, Double price, Integer stock, String photo, String description, Set purchases) {
       this.id = id;
       this.category = category;
       this.name = name;
       this.price = price;
       this.stock = stock;
       this.photo = photo;
       this.description = description;
       this.purchases = purchases;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set purchases) {
        this.purchases = purchases;
    }




}


