package dto;
// Generated Mar 21, 2014 5:50:47 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Purchase generated by hbm2java
 */
public class Purchase  implements java.io.Serializable {


     private PurchaseId id;
     private User user;
     private Product product;
     private Integer amount;
     private Date purchaseDate;
     private Date addedDate;
     private boolean ispurchased;

    public Purchase() {
    }

	
    public Purchase(PurchaseId id, User user, Product product, Date purchaseDate, Date addedDate, boolean ispurchased) {
        this.id = id;
        this.user = user;
        this.product = product;
        this.purchaseDate = purchaseDate;
        this.addedDate = addedDate;
        this.ispurchased = ispurchased;
    }
    public Purchase(PurchaseId id, User user, Product product, Integer amount, Date purchaseDate, Date addedDate, boolean ispurchased) {
       this.id = id;
       this.user = user;
       this.product = product;
       this.amount = amount;
       this.purchaseDate = purchaseDate;
       this.addedDate = addedDate;
       this.ispurchased = ispurchased;
    }
   
    public PurchaseId getId() {
        return this.id;
    }
    
    public void setId(PurchaseId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    public Date getPurchaseDate() {
        return this.purchaseDate;
    }
    
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }
    public boolean isIspurchased() {
        return this.ispurchased;
    }
    
    public void setIspurchased(boolean ispurchased) {
        this.ispurchased = ispurchased;
    }




}


