package dto;
// Generated Mar 21, 2014 5:50:47 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private String fname;
     private String lname;
     private String displayname;
     private String email;
     private String password;
     private String address;
     private Date birthdate;
     private String job;
     private double credit;
     private boolean active;
     private Set purchases = new HashSet(0);
     private Set interests = new HashSet(0);

    public User() {
    }

	
    public User(int id, String fname, String lname, String email, String password, double credit, boolean active) {
        this.id = id;
        this.fname = fname;
        this.lname = lname;
        this.email = email;
        this.password = password;
        this.credit = credit;
        this.active = active;
    }
    public User(int id, String fname, String lname, String displayname, String email, String password, String address, Date birthdate, String job, double credit, boolean active, Set purchases, Set interests) {
       this.id = id;
       this.fname = fname;
       this.lname = lname;
       this.displayname = displayname;
       this.email = email;
       this.password = password;
       this.address = address;
       this.birthdate = birthdate;
       this.job = job;
       this.credit = credit;
       this.active = active;
       this.purchases = purchases;
       this.interests = interests;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getDisplayname() {
        return this.displayname;
    }
    
    public void setDisplayname(String displayname) {
        this.displayname = displayname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }
    public double getCredit() {
        return this.credit;
    }
    
    public void setCredit(double credit) {
        this.credit = credit;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Set getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set purchases) {
        this.purchases = purchases;
    }
    public Set getInterests() {
        return this.interests;
    }
    
    public void setInterests(Set interests) {
        this.interests = interests;
    }




}


